### ISSUE TITLE
Example!

### ISSUE THREAD

**Issue by MG-Token** [fawno/SoftEtherApi-PHP#1]
hi please input a example of this api and how to connect a hub and how to create user and set password to the new user and how to get user list or confirm a user is vaild? if true check password to is vaild or what?

thanks :)

**Comment by ghost** [comment]
The function signature is mainly the same for the [https://github.com/hoppler/SoftEtherApi](https://github.com/hoppler/SoftEtherApi). Therefore the examples there can be used
