### ISSUE TITLE
Error when creating user 

### ISSUE THREAD

**Issue by safen** [fawno/SoftEtherApi-PHP#12]
Hello when I want to create new user it gave me this error : 
I'm using it in **Laravel Framework 9.47.0**
  ```
  $softEther=new SoftEtherApi\SoftEther("192.168.5.5",'999');
    $connectResult = $softEther->Connect();
    $authResult = $softEther->Authenticate('password');
    $user = $softEther->HubApi->CreateUser("vpn", "testUser", "userPw",'users','usertest','note');
    return  $user->Valid() ? "Success" : $user->Error;
```

![image](https://user-images.githubusercontent.com/6255437/212393416-c9c06783-ea18-413c-aec8-e005029f48b2.png)

**Comment by safen** [comment]
I fixed it ist bug just change the last parameter type from int to DateTime at 
**SoftEtherApi\Api\SoftEtherHub::CreateUser()** 


![image](https://user-images.githubusercontent.com/6255437/212396744-65c472aa-a8cd-4c4e-9640-9b31f3f0b0f4.png)
 

![image](https://user-images.githubusercontent.com/6255437/212397207-43c63c4b-64f9-4eac-9d8e-d0a5c96cf7cf.png)


and all information must be filled there is no optional parameter.

**Comment by alphp** [comment]
Thanks
