### ISSUE TITLE
AccessDenied

### ISSUE THREAD

**Issue by lthull** [fawno/SoftEtherApi-PHP#2]
Hi,
i am new to SoftEather Api and want to automate the user management of my server.
First i want to say thanks for this great implementation.

The connection works fine and a get the server random back. 
But if i try to authenticate the server respons with "AccessDenied" error code.
I testest the password in the SoftEther server manager and all works fine.

Is there any type of configuration i have to make so this will work?

Running SoftEther Ver 4.28 Build 9669 

Thanks for responding.

**Comment by ghost** [comment]
Hi,

i tried it with your build version under linux and could connect to vpnserver. maybe you are using unicode characters in your password which get hashed wrongly. if possible change the password to someting ascii like. 

- On which platform are you running the server: windows/linux 32bit/64bit.
- Another issue could be your php-version. Im running php 7.2

**Comment by lthull** [comment]
Hi,
yes i switch my password to ascii only but still get the error.
Nice to know that the api works with my used version.

The SoftEther Server run on Ubuntu 16.04.5 64bit.
PHP api runs on Windows 10 in MAMP 5.2 php Version 7.21.

Maybe the Windows MAMP Server is the problem.
I will check the php api on apache server.

Thanks for helping out.

**Comment by ghost** [comment]
Hi,

MAMP is for Mac, but you said Windows 10. Version 5.2 is not available for MAMP on Windows^^

**Comment by lthull** [comment]
y you're right its version 4.01 on windows ;)

**Comment by lthull** [comment]
ok on mac with mamp 5.2 it works like a charm.
Have to be something with crapy windwos server.
Time to switch.

Thanks and sorry for wasting your time ;)

**Comment by ghost** [comment]
The real issue is that your MAMP installation has a 32Bit installation of PHP, but the SHA0 algorithm for password hash creation requires 64Bit datatype sizes and thus a 64Bit PHP installation.

Thx for finding that issue

**Comment by ghost** [comment]
32Bit PHP is now supported for SHA0 by https://github.com/hoppler/SoftEtherApi-PHP/commit/9bc9c036b12b0588aaef1da4c38c78ff9c806013
