### ISSUE TITLE
How can we use this

### ISSUE THREAD

**Issue by synetalsolutions** [fawno/SoftEtherApi-PHP#3]
How can we use  this sdk to establish the connection with softether server......I managed it somehow but how we create users and give them the limited access for particular time period

**Comment by ghost** [comment]
Hi,

as seen in main.php the syntax of the c# and php api is quite the same. Like said on start page, examples are in the c# project.

I dont use the php code so it contains many errors. For example currently im fixing the issue of creating a user in php.

The C# code
```c#
var connectResult = softEther.Connect();
var authResult = softEther.Authenticate(pw);

var user = softEther.HubApi.CreateUser("testHub", "testUser", "userPw");
Console.WriteLine(user.Valid() ? "Success" : user.Error.ToString());
```

The PHP code
```php
$connectResult = $softEther->Connect();
$authResult = $softEther->Authenticate(pw);

$user = $softEther->HubApi->CreateUser("testHub", "testUser", "userPw");
echo $user->Valid() ? "Success" : $user->Error;
```

**Comment by synetalsolutions** [comment]
So overall C# code will  work fine but not php..?

**Comment by ghost** [comment]
Currently yes because im only using the c# code

**Comment by synetalsolutions** [comment]
Ok.. I will check the php code if I found some issues I will add in the github..

And I php code you added \ in main.php which is wrong you need to do / then it will find correct directory for sdk

**Comment by ghost** [comment]
I dont really understand your / \ explanation. 
I added support for create user with expire time, everything else should be only a problem of setting the correct type in the request

For example SoftEtherValueType::Raw is required for a byte array
```php
'HashedKey' => ['type' => SoftEtherValueType::Raw, 'value' => [$hashPair->Hash]],
```
