### ISSUE TITLE
some bug

### ISSUE THREAD

**Issue by mohammad-rj** [fawno/SoftEtherApi-PHP#4]
fisrt
after conect to hub
when i want to create user with this code

$user = $softEther->HubApi->CreateUser("vpn", "test6", "test");
echo $user->Valid() ? "Success" : $user->Error;

i get this error:

`
Fatal error: Uncaught TypeError: Argument 1 passed to SoftEtherApi\Infrastructure\SoftEtherConverter::DateTimeToSoftEtherLong() must be an instance of DateTime, null given, called in /var/www/html/bot/SoftEtherApi-PHP/SoftEtherApi/Api/SoftEtherHub.php on line 405 and defined in /var/www/html/bot/SoftEtherApi-PHP/SoftEtherApi/Infrastructure/SoftEtherConverter.php:7 Stack trace: #0 /var/www/html/bot/SoftEtherApi-PHP/SoftEtherApi/Api/SoftEtherHub.php(405): SoftEtherApi\Infrastructure\SoftEtherConverter::DateTimeToSoftEtherLong(NULL) #1 /var/www/html/bot/SoftEtherApi-PHP/main.php(12): SoftEtherApi\Api\SoftEtherHub->CreateUser('vpn', 'test6', 'test') #2 {main} thrown in /var/www/html/bot/SoftEtherApi-PHP/SoftEtherApi/Infrastructure/SoftEtherConverter.php on line 7
`

on file :
SoftEtherApi\Infrastructure\SoftEtherConverter function
```php
class SoftEtherConverter
    {
        public static function DateTimeToSoftEtherLong(\DateTime $date)
        {
            if($date == null)
                return null;

            $softEtherDate = $date;
            $softEtherDate->add(new \DateInterval("PT".$date->getOffset()."H"));
            $softEtherDate->sub(new \DateInterval("PT9H")); //sub 9 Hours from UTC for JAPAN Timezone which SoftEther expects
            return $softEtherDate->getTimestamp() * 1000;
        }
```

in line 7
change
        public static function DateTimeToSoftEtherLong(\DateTime $date)
to
        public static function DateTimeToSoftEtherLong(\DateTime $date=null)

and this error fixed

_______________________________________________________________________________________________________
secend
after conect to hub
when i want to create user with this code (with realname,note,expiretime)

```php
$date_expire = new DateTime("2019/01/15");
$user = $softEther->HubApi->CreateUser("vpn", "test7", "test","public","test","test",$date_expire);
echo $user->Valid() ? "Success" : $user->Error;
```

 realname and note not adding in user

for solving this problem on file :
SoftEtherApi\Api\SoftEtherHub

in line 403
change
'Realname' => ['type' => Containers\SoftEtherValueType::String, 'value' => [$realName]],
to
'Realname' => ['type' => Containers\SoftEtherValueType::UnicodeString, 'value' => [$realName]],
and line 404
'Note' => ['type' => Containers\SoftEtherValueType::String, 'value' => [$note]],
to
'Note' => ['type' => Containers\SoftEtherValueType::UnicodeString, 'value' => [$note]],
                    
after that realname and note add correctly

_______________________________________________________________________________________________________
Third
i want change password of user
using this code :

```php
$user = $softEther->HubApi->SetUserPassword("vpn", "test7", "test2");
echo $user->Valid() ? "Success" : $user->Error;
```

i get this error

`
Fatal error: Uncaught Exception: Failed to read dataLength in /var/www/html/bot/SoftEtherApi-PHP/SoftEtherApi/SoftEther.php:130 Stack trace: #0 /var/www/html/bot/SoftEtherApi-PHP/SoftEtherApi/Api/SoftEtherHub.php(450): SoftEtherApi\SoftEther->CallMethod('SetUser', Array) #1 /var/www/html/bot/SoftEtherApi-PHP/SoftEtherApi/Api/SoftEtherHub.php(421): SoftEtherApi\Api\SoftEtherHub->SetUser2('vpn', Array, Array, Array, Array, Array, Array, Array, Array, Array, Array, Array) #2 /var/www/html/bot/SoftEtherApi-PHP/SoftEtherApi/Api/SoftEtherHub.php(480): SoftEtherApi\Api\SoftEtherHub->SetUser('vpn', Object(SoftEtherApi\SoftEtherModel\HubUser)) #3 /var/www/html/bot/SoftEtherApi-PHP/main.php(16): SoftEtherApi\Api\SoftEtherHub->SetUserPassword('vpn', 'test7', 'test2') #4 {main} thrown in /var/www/html/bot/SoftEtherApi-PHP/SoftEtherApi/SoftEther.php on line 130
`

i dont know what what say it!
Please help me solve it

**Comment by ghost** [comment]
Hi,

i guess i fixed the bugs in the commit 66ceb4f93f2d2c09f5a1a1cda0d5999e224fc5ac
